name: Build

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read
  actions: write

env:
  DOTNET_VERSION: '10.0.x'
  VERSION_PREFIX: '0.2.1'
  ARTIFACT_OUTPUT: '${{ github.workspace }}/artifacts'

jobs:
  build-native:
    name: Build native framework-system rust (${{ matrix.os }} ${{ matrix.platform }})
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: Windows
            runsOn: windows-latest
            platform: win-x64
            artifactPath: framework-system-ffi-extensions/target/release/framework_lib_ffi.dll
          - os: Windows
            runsOn: windows-11-arm
            platform: win-arm64
            artifactPath: framework-system-ffi-extensions/target/release/framework_lib_ffi.dll
          - os: Linux
            runsOn: ubuntu-latest
            platform: linux-x64
            artifactPath: framework-system-ffi-extensions/target/release/libframework_lib_ffi.so
          - os: Linux
            runsOn: ubuntu-24.04-arm
            platform: linux-arm64
            artifactPath: framework-system-ffi-extensions/target/release/libframework_lib_ffi.so

    runs-on: ${{ matrix.runsOn }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup Rust with Cache
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          framework-system-ffi-extensions -> target

    - name: Install with Cache Linux Framework dependencies (libudev-dev)
      uses: awalsh128/cache-apt-pkgs-action@v1
      if: runner.os == 'Linux'
      with:
        packages: libudev-dev
        version: ${{ runner.os }}-${{ runner.arch }}

    - name: Build native library
      run: cargo build --manifest-path framework-system-ffi-extensions/Cargo.toml -p framework_lib_ffi --release

    - name: Upload native artifact
      uses: actions/upload-artifact@v7
      with:
        name: framework-dotnet-native-${{ matrix.platform }}
        path: ${{ matrix.artifactPath }}
        if-no-files-found: error

    - name: Upload generated bindings artifact
      if: matrix.platform == 'win-x64'
      uses: actions/upload-artifact@v7
      with:
        name: framework-dotnet-bindings
        path: framework-system-ffi-extensions/csharp/NativeMethods.g.cs
        if-no-files-found: error

    - name: "Cancel if failure"
      if: ${{ failure() }}
      uses: potiuk/cancel-workflow-runs@master
      with:
        cancelMode: self
        cancelFutureDuplicates: false
        selfPreservation: false
        token: ${{ secrets.GITHUB_TOKEN }}

  pack:
    name: Pack NuGet
    needs: build-native
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Download generated bindings artifact
      uses: actions/download-artifact@v8
      with:
        name: framework-dotnet-bindings
        path: framework-system-ffi-extensions/csharp

    - name: Download win-x64 native artifact
      uses: actions/download-artifact@v8
      with:
        name: framework-dotnet-native-win-x64
        path: artifacts/win-x64

    - name: Download win-arm64 native artifact
      uses: actions/download-artifact@v8
      with:
        name: framework-dotnet-native-win-arm64
        path: artifacts/win-arm64

    - name: Download linux-x64 native artifact
      uses: actions/download-artifact@v8
      with:
        name: framework-dotnet-native-linux-x64
        path: artifacts/linux-x64

    - name: Download linux-arm64 native artifact
      uses: actions/download-artifact@v8
      with:
        name: framework-dotnet-native-linux-arm64
        path: artifacts/linux-arm64

    - name: Cache and restore nugets
      uses: actions/cache@v5
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ runner.arch }}-nuget-${{ github.workflow }}-${{ github.ref }}-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-nuget-${{ github.workflow }}-${{ github.ref }}-

    - name: Restore dependencies
      run: dotnet restore -v normal --locked-mode -p:Version=${{ env.VERSION_PREFIX }}.${{ github.run_number }} -p:InformationalVersion=${{ env.VERSION_PREFIX }}.${{ github.run_number }}+${{ github.sha }} -p:DebugSymbols=true -p:DebugType=portable

    - name: Build
      run: >-
        dotnet build framework-dotnet/framework-dotnet.csproj
        -v normal
        --configuration Release
        --no-restore
        -p:Version=${{ env.VERSION_PREFIX }}.${{ github.run_number }}
        -p:InformationalVersion=${{ env.VERSION_PREFIX }}.${{ github.run_number }}+${{ github.sha }}
        -p:DebugSymbols=true
        -p:DebugType=portable
        -p:ContinuousIntegrationBuild=true
        -p:SkipRustBuild=true
        -p:FrameworkDotnetWindowsNativeLibraryPath=${{ github.workspace }}\artifacts\win-x64\framework_lib_ffi.dll
        -p:FrameworkDotnetWindowsArm64NativeLibraryPath=${{ github.workspace }}\artifacts\win-arm64\framework_lib_ffi.dll
        -p:FrameworkDotnetLinuxNativeLibraryPath=${{ github.workspace }}\artifacts\linux-x64\libframework_lib_ffi.so
        -p:FrameworkDotnetLinuxArm64NativeLibraryPath=${{ github.workspace }}\artifacts\linux-arm64\libframework_lib_ffi.so

    - name: Pack NuGet package
      run: >-
        dotnet pack framework-dotnet/framework-dotnet.csproj
        -v normal
        --configuration Release
        --no-restore
        --no-build
        --output ${{ env.ARTIFACT_OUTPUT }}
        -p:Version=${{ env.VERSION_PREFIX }}.${{ github.run_number }}
        -p:InformationalVersion=${{ env.VERSION_PREFIX }}.${{ github.run_number }}+${{ github.sha }}
        -p:DebugSymbols=true
        -p:DebugType=portable
        -p:ContinuousIntegrationBuild=true
        -p:SkipRustBuild=true
        -p:FrameworkDotnetWindowsNativeLibraryPath=${{ github.workspace }}\artifacts\win-x64\framework_lib_ffi.dll
        -p:FrameworkDotnetWindowsArm64NativeLibraryPath=${{ github.workspace }}\artifacts\win-arm64\framework_lib_ffi.dll
        -p:FrameworkDotnetLinuxNativeLibraryPath=${{ github.workspace }}\artifacts\linux-x64\libframework_lib_ffi.so
        -p:FrameworkDotnetLinuxArm64NativeLibraryPath=${{ github.workspace }}\artifacts\linux-arm64\libframework_lib_ffi.so

    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v7
      with:
        name: framework-dotnet-nuget
        path: ${{ env.ARTIFACT_OUTPUT }}
        if-no-files-found: error
    - name: Push nugets to Github
      run: |
        nuget sources Add -Name "GitHub" -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -Username "${{ github.actor }}" -Password "${{ secrets.GITHUB_TOKEN }}"
        nuget push "${{ env.ARTIFACT_OUTPUT }}/**/*.nupkg" -Source "GitHub"

  clean-up:
    name: Cleans up artifacts
    needs: pack
    runs-on: ubuntu-latest
    if: ${{ always() }}
    
    steps:
    - name: Deletes generated bindings artifact
      uses: geekyeggo/delete-artifact@v6
      if: ${{ always() }}
      with:
        name: framework-dotnet-bindings
        failOnError: false

    - name: Deletes win-x64 native artifact
      uses: geekyeggo/delete-artifact@v6
      if: ${{ always() }}
      with:
        name: framework-dotnet-native-win-x64
        failOnError: false

    - name: Deletes win-arm64 native artifact
      uses: geekyeggo/delete-artifact@v6
      if: ${{ always() }}
      with:
        name: framework-dotnet-native-win-arm64
        failOnError: false

    - name: Deletes linux-x64 native artifact
      uses: geekyeggo/delete-artifact@v6
      if: ${{ always() }}
      with:
        name: framework-dotnet-native-linux-x64
        failOnError: false

    - name: Deletes linux-arm64 native artifact
      uses: geekyeggo/delete-artifact@v6
      if: ${{ always() }}
      with:
        name: framework-dotnet-native-linux-arm64
        failOnError: false
